name: ci

on:
  push:
    tags:
      - '*'
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # More info about the environment variables in the README
          # https://github.com/goreleaser/goreleaser-action
          # Enable auto-snapshot mode for non-tag pushes
          SNAPSHOT: ${{ !startsWith(github.ref, 'refs/tags/') }}